// Copyright 2013-2023, University of Colorado Boulder

/**
 * Module that includes all Kite dependencies, so that requiring this module will return an object
 * that consists of the entire exported 'kite' namespace API.
 *
 * The API is actually generated by the 'kite' module, so if this module (or all other modules) are
 * not included, the 'kite' namespace may not be complete.
 *
 * @author Jonathan Olson <jonathan.olson@colorado.edu>
 */


import kite from '@/utils/kite/kite';
import '@/utils/kite/ops/Boundary';
import '@/utils/kite/ops/BoundsIntersection';
import '@/utils/kite/ops/Edge';
import '@/utils/kite/ops/Face';
import '@/utils/kite/ops/Graph';
import '@/utils/kite/ops/HalfEdge';
import '@/utils/kite/ops/Loop';
import '@/utils/kite/ops/SegmentTree';
import '@/utils/kite/ops/Vertex';
import '@/utils/kite/parser/svgPath';
import '@/utils/kite/segments/Arc';
import '@/utils/kite/segments/Cubic';
import '@/utils/kite/segments/EllipticalArc';
import '@/utils/kite/segments/Line';
import '@/utils/kite/segments/Quadratic';
import '@/utils/kite/segments/Segment';
import '@/utils/kite/Shape';
import '@/utils/kite/util/intersectConicMatrices';
import '@/utils/kite/util/LineStyles';
import '@/utils/kite/util/Overlap';
import '@/utils/kite/util/SegmentIntersection';
import '@/utils/kite/util/Subpath';

// note: the kite variable is filled in as modules are visited
export default kite;