// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import addressBookRegularString from '@/utils/sherpa/fontawesome-5/addressBookRegularString';

export default new Shape(addressBookRegularString).makeImmutable();
