// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import addressCardSolidString from '@/utils/sherpa/fontawesome-5/addressCardSolidString';

export default new Shape(addressCardSolidString).makeImmutable();
