// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import addressBookSolidString from '@/utils/sherpa/fontawesome-5/addressBookSolidString';

export default new Shape(addressBookSolidString).makeImmutable();
