// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import addressCardRegularString from '@/utils/sherpa/fontawesome-5/addressCardRegularString';

export default new Shape(addressCardRegularString).makeImmutable();
