// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import adSolidString from '@/utils/sherpa/fontawesome-5/adSolidString';

export default new Shape(adSolidString).makeImmutable();
