// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import airFreshenerSolidString from '@/utils/sherpa/fontawesome-5/airFreshenerSolidString';

export default new Shape(airFreshenerSolidString).makeImmutable();
