// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import alignJustifySolidString from '@/utils/sherpa/fontawesome-5/alignJustifySolidString';

export default new Shape(alignJustifySolidString).makeImmutable();
