// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import alignCenterSolidString from '@/utils/sherpa/fontawesome-5/alignCenterSolidString';

export default new Shape(alignCenterSolidString).makeImmutable();
