// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import arrowRightSolidString from '@/utils/sherpa/fontawesome-5/arrowRightSolidString.js';

export default new Shape( arrowRightSolidString ).makeImmutable();