// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import arrowAltCircleLeftSolidString from '@/utils/sherpa/fontawesome-5/arrowAltCircleLeftSolidString.js';

export default new Shape( arrowAltCircleLeftSolidString ).makeImmutable();