// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import assistiveListeningSystemsSolidString from '@/utils/sherpa/fontawesome-5/assistiveListeningSystemsSolidString.js';

export default new Shape( assistiveListeningSystemsSolidString ).makeImmutable();