// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import babyCarriageSolidString from '@/utils/sherpa/fontawesome-5/babyCarriageSolidString.js';

export default new Shape( babyCarriageSolidString ).makeImmutable();