// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import babySolidString from '@/utils/sherpa/fontawesome-5/babySolidString.js';

export default new Shape( babySolidString ).makeImmutable();