// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import balanceScaleRightSolidString from '@/utils/sherpa/fontawesome-5/balanceScaleRightSolidString.js';

export default new Shape( balanceScaleRightSolidString ).makeImmutable();