// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import bathSolidString from '@/utils/sherpa/fontawesome-5/bathSolidString.js';

export default new Shape( bathSolidString ).makeImmutable();