// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import batteryQuarterSolidString from '@/utils/sherpa/fontawesome-5/batteryQuarterSolidString.js';

export default new Shape( batteryQuarterSolidString ).makeImmutable();