// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import bellSlashSolidString from '@/utils/sherpa/fontawesome-5/bellSlashSolidString.js';

export default new Shape( bellSlashSolidString ).makeImmutable();