// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import binocularsSolidString from '@/utils/sherpa/fontawesome-5/binocularsSolidString.js';

export default new Shape( binocularsSolidString ).makeImmutable();