// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import blindSolidString from '@/utils/sherpa/fontawesome-5/blindSolidString.js';

export default new Shape( blindSolidString ).makeImmutable();