// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import bookDeadSolidString from '@/utils/sherpa/fontawesome-5/bookDeadSolidString.js';

export default new Shape( bookDeadSolidString ).makeImmutable();