// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import calendarWeekSolidString from '@/utils/sherpa/fontawesome-5/calendarWeekSolidString.js';

export default new Shape( calendarWeekSolidString ).makeImmutable();