// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import chartLineSolidString from '@/utils/sherpa/fontawesome-5/chartLineSolidString.js';

export default new Shape( chartLineSolidString ).makeImmutable();