// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import chevronCircleRightSolidString from '@/utils/sherpa/fontawesome-5/chevronCircleRightSolidString.js';

export default new Shape( chevronCircleRightSolidString ).makeImmutable();