// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import chevronLeftSolidString from '@/utils/sherpa/fontawesome-5/chevronLeftSolidString.js';

export default new Shape( chevronLeftSolidString ).makeImmutable();