// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import clipboardRegularString from '@/utils/sherpa/fontawesome-5/clipboardRegularString.js';

export default new Shape( clipboardRegularString ).makeImmutable();