// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import cloudShowersHeavySolidString from '@/utils/sherpa/fontawesome-5/cloudShowersHeavySolidString.js';

export default new Shape( cloudShowersHeavySolidString ).makeImmutable();