// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import cloudMeatballSolidString from '@/utils/sherpa/fontawesome-5/cloudMeatballSolidString.js';

export default new Shape( cloudMeatballSolidString ).makeImmutable();