// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import codeSolidString from '@/utils/sherpa/fontawesome-5/codeSolidString.js';

export default new Shape( codeSolidString ).makeImmutable();