// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import codeBranchSolidString from '@/utils/sherpa/fontawesome-5/codeBranchSolidString.js';

export default new Shape( codeBranchSolidString ).makeImmutable();