// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import cropSolidString from '@/utils/sherpa/fontawesome-5/cropSolidString.js';

export default new Shape( cropSolidString ).makeImmutable();