// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import crutchSolidString from '@/utils/sherpa/fontawesome-5/crutchSolidString.js';

export default new Shape( crutchSolidString ).makeImmutable();