// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import diceD20SolidString from '@/utils/sherpa/fontawesome-5/diceD20SolidString.js';

export default new Shape( diceD20SolidString ).makeImmutable();