// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import diceD6SolidString from '@/utils/sherpa/fontawesome-5/diceD6SolidString.js';

export default new Shape( diceD6SolidString ).makeImmutable();