// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import donateSolidString from '@/utils/sherpa/fontawesome-5/donateSolidString.js';

export default new Shape( donateSolidString ).makeImmutable();