// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import dumpsterSolidString from '@/utils/sherpa/fontawesome-5/dumpsterSolidString.js';

export default new Shape( dumpsterSolidString ).makeImmutable();