// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import eggSolidString from '@/utils/sherpa/fontawesome-5/eggSolidString.js';

export default new Shape( eggSolidString ).makeImmutable();