// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import fileAltRegularString from '@/utils/sherpa/fontawesome-5/fileAltRegularString.js';

export default new Shape( fileAltRegularString ).makeImmutable();