// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import fileArchiveRegularString from '@/utils/sherpa/fontawesome-5/fileArchiveRegularString.js';

export default new Shape( fileArchiveRegularString ).makeImmutable();