// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import fileInvoiceSolidString from '@/utils/sherpa/fontawesome-5/fileInvoiceSolidString.js';

export default new Shape( fileInvoiceSolidString ).makeImmutable();