// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import folderRegularString from '@/utils/sherpa/fontawesome-5/folderRegularString.js';

export default new Shape( folderRegularString ).makeImmutable();