// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import frogSolidString from '@/utils/sherpa/fontawesome-5/frogSolidString.js';

export default new Shape( frogSolidString ).makeImmutable();