// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import globeAfricaSolidString from '@/utils/sherpa/fontawesome-5/globeAfricaSolidString.js';

export default new Shape( globeAfricaSolidString ).makeImmutable();