// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../kite/imports';
import globeSolidString from './globeSolidString';

export default new Shape(globeSolidString).makeImmutable();
