// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import globeSolidString from '@/utils/sherpa/fontawesome-5/globeSolidString';

export default new Shape(globeSolidString).makeImmutable();
