// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import golfBallSolidString from '@/utils/sherpa/fontawesome-5/golfBallSolidString.js';

export default new Shape( golfBallSolidString ).makeImmutable();