// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import grinSquintTearsRegularString from '@/utils/sherpa/fontawesome-5/grinSquintTearsRegularString.js';

export default new Shape( grinSquintTearsRegularString ).makeImmutable();