// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import gripLinesSolidString from '@/utils/sherpa/fontawesome-5/gripLinesSolidString.js';

export default new Shape( gripLinesSolidString ).makeImmutable();