// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import guitarSolidString from '@/utils/sherpa/fontawesome-5/guitarSolidString.js';

export default new Shape( guitarSolidString ).makeImmutable();