// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import hamburgerSolidString from '@/utils/sherpa/fontawesome-5/hamburgerSolidString.js';

export default new Shape( hamburgerSolidString ).makeImmutable();