// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import handScissorsRegularString from '@/utils/sherpa/fontawesome-5/handScissorsRegularString.js';

export default new Shape( handScissorsRegularString ).makeImmutable();