// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import handshakeAltSlashSolidString from '@/utils/sherpa/fontawesome-5/handshakeAltSlashSolidString.js';

export default new Shape( handshakeAltSlashSolidString ).makeImmutable();