// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import handPointLeftSolidString from '@/utils/sherpa/fontawesome-5/handPointLeftSolidString.js';

export default new Shape( handPointLeftSolidString ).makeImmutable();