// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import handPointDownSolidString from '@/utils/sherpa/fontawesome-5/handPointDownSolidString.js';

export default new Shape( handPointDownSolidString ).makeImmutable();