// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import headphonesAltSolidString from '@/utils/sherpa/fontawesome-5/headphonesAltSolidString.js';

export default new Shape( headphonesAltSolidString ).makeImmutable();