// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import heartSolidString from '@/utils/sherpa/fontawesome-5/heartSolidString.js';

export default new Shape( heartSolidString ).makeImmutable();