// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../kite/imports';
import homeSolidString from './homeSolidString';

export default new Shape(homeSolidString).makeImmutable();
