// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import homeSolidString from '@/utils/sherpa/fontawesome-5/homeSolidString';

export default new Shape(homeSolidString).makeImmutable();
