// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import hospitalRegularString from '@/utils/sherpa/fontawesome-5/hospitalRegularString.js';

export default new Shape( hospitalRegularString ).makeImmutable();