// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import imagesRegularString from '@/utils/sherpa/fontawesome-5/imagesRegularString.js';

export default new Shape( imagesRegularString ).makeImmutable();