// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import jointSolidString from '@/utils/sherpa/fontawesome-5/jointSolidString.js';

export default new Shape( jointSolidString ).makeImmutable();