// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import laughSquintRegularString from '@/utils/sherpa/fontawesome-5/laughSquintRegularString.js';

export default new Shape( laughSquintRegularString ).makeImmutable();