// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import listAltSolidString from '@/utils/sherpa/fontawesome-5/listAltSolidString.js';

export default new Shape( listAltSolidString ).makeImmutable();