// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import lockSolidString from '@/utils/sherpa/fontawesome-5/lockSolidString';

export default new Shape(lockSolidString).makeImmutable();
