// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import mapMarkerAltSolidString from '@/utils/sherpa/fontawesome-5/mapMarkerAltSolidString';

export default new Shape(mapMarkerAltSolidString).makeImmutable();
