// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../kite/imports';
import mapMarkerAltSolidString from './mapMarkerAltSolidString';

export default new Shape(mapMarkerAltSolidString).makeImmutable();
