// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import mehRegularString from '@/utils/sherpa/fontawesome-5/mehRegularString.js';

export default new Shape( mehRegularString ).makeImmutable();