// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import mobileAltSolidString from '@/utils/sherpa/fontawesome-5/mobileAltSolidString.js';

export default new Shape( mobileAltSolidString ).makeImmutable();