// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import musicSolidString from '@/utils/sherpa/fontawesome-5/musicSolidString.js';

export default new Shape( musicSolidString ).makeImmutable();