// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import networkWiredSolidString from '@/utils/sherpa/fontawesome-5/networkWiredSolidString.js';

export default new Shape( networkWiredSolidString ).makeImmutable();