// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import newspaperRegularString from '@/utils/sherpa/fontawesome-5/newspaperRegularString.js';

export default new Shape( newspaperRegularString ).makeImmutable();