// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import pawSolidString from '@/utils/sherpa/fontawesome-5/pawSolidString.js';

export default new Shape( pawSolidString ).makeImmutable();