// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import peopleArrowsSolidString from '@/utils/sherpa/fontawesome-5/peopleArrowsSolidString.js';

export default new Shape( peopleArrowsSolidString ).makeImmutable();