// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import prescriptionBottleAltSolidString from '@/utils/sherpa/fontawesome-5/prescriptionBottleAltSolidString.js';

export default new Shape( prescriptionBottleAltSolidString ).makeImmutable();