// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import pumpSoapSolidString from '@/utils/sherpa/fontawesome-5/pumpSoapSolidString.js';

export default new Shape( pumpSoapSolidString ).makeImmutable();