// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import quidditchSolidString from '@/utils/sherpa/fontawesome-5/quidditchSolidString.js';

export default new Shape( quidditchSolidString ).makeImmutable();