// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import schoolSolidString from '@/utils/sherpa/fontawesome-5/schoolSolidString.js';

export default new Shape( schoolSolidString ).makeImmutable();