// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import slidersHSolidString from '@/utils/sherpa/fontawesome-5/slidersHSolidString.js';

export default new Shape( slidersHSolidString ).makeImmutable();