// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import smileBeamRegularString from '@/utils/sherpa/fontawesome-5/smileBeamRegularString.js';

export default new Shape( smileBeamRegularString ).makeImmutable();