// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import smogSolidString from '@/utils/sherpa/fontawesome-5/smogSolidString.js';

export default new Shape( smogSolidString ).makeImmutable();