// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import sortNumericUpAltSolidString from '@/utils/sherpa/fontawesome-5/sortNumericUpAltSolidString.js';

export default new Shape( sortNumericUpAltSolidString ).makeImmutable();