// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import sprayCanSolidString from '@/utils/sherpa/fontawesome-5/sprayCanSolidString.js';

export default new Shape( sprayCanSolidString ).makeImmutable();