// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import starSolidString from '@/utils/sherpa/fontawesome-5/starSolidString.js';

export default new Shape( starSolidString ).makeImmutable();