// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import stopwatch20SolidString from '@/utils/sherpa/fontawesome-5/stopwatch20SolidString.js';

export default new Shape( stopwatch20SolidString ).makeImmutable();