// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import subscriptSolidString from '@/utils/sherpa/fontawesome-5/subscriptSolidString.js';

export default new Shape( subscriptSolidString ).makeImmutable();