// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import timesCircleSolidString from '@/utils/sherpa/fontawesome-5/timesCircleSolidString.js';

export default new Shape( timesCircleSolidString ).makeImmutable();