// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import torahSolidString from '@/utils/sherpa/fontawesome-5/torahSolidString.js';

export default new Shape( torahSolidString ).makeImmutable();