// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import trophySolidString from '@/utils/sherpa/fontawesome-5/trophySolidString.js';

export default new Shape( trophySolidString ).makeImmutable();