// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '../../kite/imports';
import unlockSolidString from './unlockSolidString';

export default new Shape(unlockSolidString).makeImmutable();
