// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import userTimesSolidString from '@/utils/sherpa/fontawesome-5/userTimesSolidString.js';

export default new Shape( userTimesSolidString ).makeImmutable();