// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import usersSlashSolidString from '@/utils/sherpa/fontawesome-5/usersSlashSolidString.js';

export default new Shape( usersSlashSolidString ).makeImmutable();