// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import userPlusSolidString from '@/utils/sherpa/fontawesome-5/userPlusSolidString.js';

export default new Shape( userPlusSolidString ).makeImmutable();