// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import yenSignSolidString from '@/utils/sherpa/fontawesome-5/yenSignSolidString.js';

export default new Shape( yenSignSolidString ).makeImmutable();