// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import algoliaString from '@/utils/sherpa/fontawesome-5/brands/algoliaString.js';

export default new Shape( algoliaString ).makeImmutable();