// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import amazonString from '@/utils/sherpa/fontawesome-5/brands/amazonString.js';

export default new Shape( amazonString ).makeImmutable();