// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import aviatoString from '@/utils/sherpa/fontawesome-5/brands/aviatoString.js';

export default new Shape( aviatoString ).makeImmutable();