// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import bloggerBString from '@/utils/sherpa/fontawesome-5/brands/bloggerBString.js';

export default new Shape( bloggerBString ).makeImmutable();