// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import cloudflareString from '@/utils/sherpa/fontawesome-5/brands/cloudflareString.js';

export default new Shape( cloudflareString ).makeImmutable();