// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import css3String from '@/utils/sherpa/fontawesome-5/brands/css3String.js';

export default new Shape( css3String ).makeImmutable();