// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import dhlString from '@/utils/sherpa/fontawesome-5/brands/dhlString.js';

export default new Shape( dhlString ).makeImmutable();