// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import diasporaString from '@/utils/sherpa/fontawesome-5/brands/diasporaString.js';

export default new Shape( diasporaString ).makeImmutable();