// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import draft2DigitalString from '@/utils/sherpa/fontawesome-5/brands/draft2DigitalString.js';

export default new Shape( draft2DigitalString ).makeImmutable();