// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import fa500PxString from '@/utils/sherpa/fontawesome-5/brands/fa500PxString.js';

export default new Shape( fa500PxString ).makeImmutable();