// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import flyString from '@/utils/sherpa/fontawesome-5/brands/flyString.js';

export default new Shape( flyString ).makeImmutable();