// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import fonticonsString from '@/utils/sherpa/fontawesome-5/brands/fonticonsString.js';

export default new Shape( fonticonsString ).makeImmutable();