// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import goodreadsGString from '@/utils/sherpa/fontawesome-5/brands/goodreadsGString.js';

export default new Shape( goodreadsGString ).makeImmutable();