// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import html5String from '@/utils/sherpa/fontawesome-5/brands/html5String.js';

export default new Shape( html5String ).makeImmutable();