// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import ns8String from '@/utils/sherpa/fontawesome-5/brands/ns8String.js';

export default new Shape( ns8String ).makeImmutable();