// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import page4String from '@/utils/sherpa/fontawesome-5/brands/page4String.js';

export default new Shape( page4String ).makeImmutable();