// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import speakerDeckString from '@/utils/sherpa/fontawesome-5/brands/speakerDeckString.js';

export default new Shape( speakerDeckString ).makeImmutable();