// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import theRedYetiString from '@/utils/sherpa/fontawesome-5/brands/theRedYetiString.js';

export default new Shape( theRedYetiString ).makeImmutable();