// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import vimeoVString from '@/utils/sherpa/fontawesome-5/brands/vimeoVString.js';

export default new Shape( vimeoVString ).makeImmutable();