// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import vnvString from '@/utils/sherpa/fontawesome-5/brands/vnvString.js';

export default new Shape( vnvString ).makeImmutable();