// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import whmcsString from '@/utils/sherpa/fontawesome-5/brands/whmcsString.js';

export default new Shape( whmcsString ).makeImmutable();