// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import yammerString from '@/utils/sherpa/fontawesome-5/brands/yammerString.js';

export default new Shape( yammerString ).makeImmutable();