// Copyright 2021, University of Colorado Boulder

// Auto-generated by modulifyFontAwesomeIcons.js, please do not modify directly.

import { Shape } from '@/utils/kite/imports';
import zhihuString from '@/utils/sherpa/fontawesome-5/brands/zhihuString.js';

export default new Shape( zhihuString ).makeImmutable();